name: Push to Branch

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to checkout the repository

    - name: Push to Different Branch
      run: |
        git config --global user.name "utkarsh-tf141"
        git config --global user.email "utkarshm21@iitk.ac.in"
        git checkout -b dummy  # Replace <new_branch_name> with the name of the branch you want to push to
        git add .
        git commit -m "Syncing with main"
        git push origin dummy  # Replace <new_branch_name> with the name of the branch you want to push to
